client_secret: urYv008mSrmYM6UynreWbf4iTQS5g0Uj
debug: false
disable_auto_update: false
disable_command_execute: false
disable_force_update: false
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: false
ip_report_period: 1800
report_delay: 3
self_update_period: 0
server: nezha.jacklou.dpdns:443
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: true
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: b28db305-6c91-44a8-89f6-0c7d56fdd568